CREATE TABLE IF NOT EXISTS patient_history (
                                                id BIGINT PRIMARY KEY,
                                                user_id BIGINT,
                                                age BIGINT,
                                                gender VARCHAR(50) NOT NULL,
                                                heart_problems BOOLEAN,
                                                chest_pain BOOLEAN,
                                                diabetes BOOLEAN,
                                                asthma BOOLEAN,
                                                hypertension BOOLEAN,
                                                taking_medications BOOLEAN,
                                                allergies_have BOOLEAN,
                                                operations BOOLEAN,
                                                hereditary_diseases BOOLEAN,
                                                hereditary_diabetes BOOLEAN,
                                                smoking VARCHAR(50),
                                                drinking_alcohol VARCHAR(50),
                                                often_play_sports VARCHAR(50),
                                                food_type VARCHAR(50),
                                                how_often_do_eat VARCHAR(50),
                                                mood_disorder BOOLEAN,
                                                psycho_emotional_state VARCHAR(50),
                                                psychotropic_drugs BOOLEAN,
                                                FOREIGN KEY ( user_id ) REFERENCES users(id)
)